spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://106.15.56.251:3306/springboot_cache
  redis:
    host: 106.15.56.251
#开启驼峰命名规则
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#打印sql
logging:
  level:
    com.atguigu.springboot.mapper: debug
#观察哪些配置类生效
debug: true